<?php
/**
 * @var Nikolay\Promotion\Block\Promotion $block
 */

$sum = 100;

?>
<script type="text/x-magento-init">
{
            "*": {
                "generate": {}
            },

            "#copy": {
                "copy": {}
            }
}
</script>
<?php if($block->getConfValue()) :?>

<div class="promo-content">
    <div class="right-content-promotion-column">
        <form class="form" action="/" method="post">
            <p><?=$block->escapeHtml(__('Refer a friend using this unique link'))?></p>
            <div style="display: flex; gap: 10px">
                <input type="text" id="unique_link" value="">
                <input type="submit" id="generate" value="GENERATE">
                <input style="display: none" type="submit" id="copy" value="COPY">
            </div>
        </form>

        <p><?=$block->escapeHtml(__('Share your unique link on social'))?></p>
        <div class="social-links">
            <img src="https://toppng.com/uploads/preview/facebook-icon-white-circle-facebook-logo-11562983298tkkvnplpku.png" alt="">
            <img src="https://image.flaticon.com/icons/png/512/60/60580.png" alt="">
        </div>
    </div>
    <div class="left-content-promotion-column">
        <div class="earned-promo-block">
            <h3><?=$sum . '$';?></h3>
            <h4><?=$block->escapeHtml(__('EARNED'))?></h4>
        </div>
        <div class="achievement-promo-block">
            <p><?=$block->escapeHtml(__('Your achievement'))?></p>
            <div class="achievement-promo-ul-block">
                <ul class="title-ul-list">
                    <li><?=$block->escapeHtml(__('Referral click'))?></li>
                    <li><?=$block->escapeHtml(__('Referral Pending'))?></li>
                    <li><?=$block->escapeHtml(__('Referral approved'))?></li>
                </ul>
                <ul class="count-ul-list">
                    <li>3</li>
                    <li>0</li>
                    <li>0</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<?php endif; ?>
