<?php
/**
 * @var Nikolay\Brand\Block\Brand $block
 */
?>

<?php

$idValue = $block->getParam();
if(!is_null($idValue)) :
    $brand = $block->getBrandPage(); ?>
    <div class="brands">
       <img class="img" style="width: 300px" src="<?=$brand->getImageUrls()?>" alt="">
       <h1 class="brand_name"><?=$brand->getName()?></h1>
       <p class="desc"><?=$brand->getDescription()?></p>
    </div>
<?php else :
    $brands = $block->getBrandPage();?>
    <div class="brands">'
    <?php foreach ($brands as $brand) : ?>
        <a class="brand" href="<?=$block->getUrl('brands/' .$brand->getName(). '.html')?>">
          <img class="img" src="<?=$brand->getImageUrls()?>" alt="">
        </a>
    <?php endforeach;?>
    </div>
<?php endif;?>