<?php
/**
 * @var Nikolay\Brand\Block\Brand $block
 */
?>
<script type="text/x-magento-init">
{
    "#accordion-brand": {
            "accordion":
            {
                "active": 1,
                "deactivate": 1
            }
    }
}
</script>
<?php

$brands = $block->getBrandPage();?>
<div id="accordion-brand" class="brands">
    <div class="brands-list">
        <?php foreach ($brands as $brand) : ?>
        <div data-role="collapsible">
            <div class="brand-title" data-role="title">
                <img src="<?=$brand->getImageUrls()?>" alt="">
            </div>
        </div>
        <?php endforeach;?>
        </div>
    <?php foreach ($brands as $brand) : ?>
    <div class="brand-content" data-role="content">
        <img style="width: 200px" src="<?=$brand->getImageUrls()?>" alt="">
        <div>
            <h2><?=$brand->getBrandName()?></h2>
            <p class="desc"><?=$brand->getDescription()?></p>
        </div>
    </div>
<?php endforeach;?>
</div>